name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Use the PHP version your project requires
          extensions: mbstring, dom, fileinfo, mysql # Add any required PHP extensions
          coverage: none

      # Step 3: Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Step 4: Set up environment
      - name: Set up environment
        run: |
          cp .env.example .env
          php artisan key:generate

      # Step 5: Run migrations
      - name: Run migrations
        run: php artisan migrate --env=testing

      # Step 6: Run tests
      - name: Run tests
        run: php artisan test